In [1]:
import pandas as pd

In [2]:
#Primer elección de dataset original con el que empezó el proyecto 
df = pd.read_csv("/Users/Intel/Desktop/DATA SCIENCE/all_seasons.csv",index_col=0)

##  NUEVA ENTREGA - Desafío APIS

In [3]:
# Trabajamos con el siguiente repositorio:  https://github.com/swar/nba_api
# Instalamos la nba_api para trabajar con los datos que nos interesan y luego importamos
from nba_api.stats.static import players

Ejemplo jugador: Giannis Antetokoumpo (Grecia)

In [4]:
player_dict = players.get_active_players() # diccionario de los jugadores activos de la liga

In [5]:
giannis = [player for player in player_dict if player["full_name"] == "Giannis Antetokounmpo"][0]

giannis_id=giannis["id"]
print(giannis_id) #vamos a trabajar con los id de jugadores y equipo para este desafio

203507

Ejemplo equipo: Denver Nuggets

In [6]:
from nba_api.stats.static import teams
team_dict=teams.get_teams()

In [7]:
DEN = [team for team in team_dict if team["full_name"] == "Denver Nuggets"][0]
DEN_id=DEN["id"]
print(DEN_id)

1610612743

## Generacion de Dataframes a partir de los ejemplos

Giannis Antetokoumpo - GameLogs

In [8]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.library.parameters import SeasonAll

In [9]:
##Gamelog de temporada 2015 de Giannis Antetokoumpo
gamelog_giannis_2015 = playergamelog.PlayerGameLog(player_id="203507",season="2015") #utilizamos parametros para seleccionar una temporada en particular
gamelog_giannis_2015_df = gamelog_giannis.get_data_frames()[0]

gamelog_giannis_2015_df.head(5)

NameError: name 'gamelog_giannis' is not defined

In [10]:
#Gamelog de todas las temporadas de Giannis Antetokoumpo

gamelog_giannis_all = playergamelog.PlayerGameLog(player_id="203507",season= SeasonAll.all) #TODAS las temporadas del jugador
gamelog_giannis_all_df = gamelog_giannis_all.get_data_frames()[0]

gamelog_giannis_all_df

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22022,203507,0022201174,"APR 02, 2023",MIL vs. PHI,W,32,13,17,0.765,...,12,14,6,1,3,4,5,33,21,1
1,22022,203507,0022201146,"MAR 30, 2023",MIL vs. BOS,L,25,11,27,0.407,...,6,7,2,1,1,0,2,24,-32,1
2,22022,203507,0022201136,"MAR 29, 2023",MIL @ IND,W,32,14,18,0.778,...,14,17,12,1,0,5,1,38,20,1
3,22022,203507,0022201109,"MAR 25, 2023",MIL @ DEN,L,32,13,22,0.591,...,8,9,4,4,0,4,2,31,-15,1
4,22022,203507,0022201102,"MAR 24, 2023",MIL @ UTA,W,25,10,13,0.769,...,5,6,11,2,0,4,3,24,32,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,22013,203507,0021300111,"NOV 13, 2013",MIL @ ORL,L,19,1,2,0.500,...,1,2,1,2,0,1,0,6,-5,1
714,22013,203507,0021300107,"NOV 12, 2013",MIL @ MIA,L,22,4,8,0.500,...,2,4,0,0,0,3,1,11,-1,1
715,22013,203507,0021300037,"NOV 02, 2013",MIL vs. TOR,L,17,1,2,0.500,...,2,2,0,1,0,0,1,2,6,0
716,22013,203507,0021300024,"NOV 01, 2013",MIL @ BOS,W,12,2,5,0.400,...,2,2,0,0,0,0,3,5,11,1
717,22013,203507,0021300008,"OCT 30, 2013",MIL @ NYK,L,5,0,0,0.000,...,0,0,0,0,0,1,2,1,-3,1

Denver Nuggets - GameLogs

In [11]:
from nba_api.stats.endpoints import leaguegamefinder

In [12]:
DEN_games=leaguegamefinder.LeagueGameFinder(team_id_nullable=DEN_id).get_data_frames()[0]

DEN_games #Todas las fichas de partidos (GameLogs) de los Denver Nuggets

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22022,1610612743,DEN,Denver Nuggets,0022201175,2023-04-02,DEN vs. GSW,W,239,112,...,0.833,17,30,47,24,11,7,11,17,2.0
1,22022,1610612743,DEN,Denver Nuggets,0022201160,2023-03-31,DEN @ PHX,L,238,93,...,0.550,15,36,51,19,11,5,11,16,-7.0
2,22022,1610612743,DEN,Denver Nuggets,0022201147,2023-03-30,DEN vs. NOP,L,242,88,...,0.625,11,29,40,21,4,5,9,21,-19.0
3,22022,1610612743,DEN,Denver Nuggets,0022201126,2023-03-27,DEN vs. PHI,W,241,116,...,0.864,10,32,42,34,8,4,12,16,5.0
4,22022,1610612743,DEN,Denver Nuggets,0022201109,2023-03-25,DEN vs. MIL,W,240,129,...,0.714,7,41,48,28,4,3,10,18,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3574,21983,1610612743,DEN,Denver Nuggets,0028300054,1983-11-05,DEN vs. SDC,W,240,127,...,0.893,10,36,46,34,6,4,16,22,NaN
3575,21983,1610612743,DEN,Denver Nuggets,0028300037,1983-11-03,DEN @ KCK,W,240,131,...,0.735,19,26,45,36,13,4,19,35,NaN
3576,21983,1610612743,DEN,Denver Nuggets,0028300026,1983-11-01,DEN vs. DAL,L,240,124,...,0.828,18,28,46,20,6,4,18,30,NaN
3577,21983,1610612743,DEN,Denver Nuggets,0028300016,1983-10-29,DEN @ SDC,L,240,128,...,0.962,8,20,28,30,9,2,12,34,NaN
3578,21983,1610612743,DEN,Denver Nuggets,0028300009,1983-10-28,DEN vs. UTH,W,240,139,...,0.744,19,37,56,40,4,8,11,26,NaN

In [13]:
from nba_api.stats.endpoints import PlayerDashboardByYearOverYear

# set the season and measure type
season = '2019-20'

# get the player stats for the specified season and measure type
player_stats = PlayerDashboardByYearOverYear(season=season, measure_type_detailed="Advanced",player_id=203507)
player_stats_df = player_stats.get_data_frames()[0]

In [14]:
player_stats_df.columns

Index(['GROUP_SET', 'GROUP_VALUE', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'MAX_GAME_DATE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING',
       'OFF_RATING', 'sp_work_OFF_RATING', 'E_DEF_RATING', 'DEF_RATING',
       'sp_work_DEF_RATING', 'E_NET_RATING', 'NET_RATING',
       'sp_work_NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT',
       'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'E_TOV_PCT', 'EFG_PCT', 'TS_PCT',
       'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'sp_work_PACE',
       'PIE', 'POSS', 'FGM', 'FGA', 'FGM_PG', 'FGA_PG', 'FG_PCT', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK',
       'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK',
       'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK',
       'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK',
       'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK',
       'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK',
       'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK',
       'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK',
       'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK'],
      dtype='object')

In [15]:
from nba_api.stats.endpoints import LeagueDashPlayerStats

In [16]:
columns = ["PLAYER_ID", "PLAYER_NAME", "TEAM_ID", "TEAM_ABBREVIATION", "AGE", "GP", "W", "L", "W_PCT", "MIN", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "TOV", "STL", "BLK", "BLKA", "PF", "PFD", "PTS", "PLUS_MINUS"]

In [17]:
#Database goes from 1996-1997 to 2021-2022

# set the desired season and team
season = "2021-22"

# retrieve data from the API
player_stats = LeagueDashPlayerStats(season=season,per_mode_detailed="PerGame")
player_stats_2022 = player_stats.get_data_frames()[0]
player_stats_2022 = player_stats_2022[columns]
print(player_stats_2022)

     PLAYER_ID      PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W  \
0       203932     Aaron Gordon  1610612743               DEN  26.0  75  46
1      1630565      Aaron Henry  1610612755               PHI  22.0   6   6
2      1628988    Aaron Holiday  1610612756               PHX  25.0  63  34
3      1630174    Aaron Nesmith  1610612738               BOS  22.0  52  32
4      1630598    Aaron Wiggins  1610612760               OKC  23.0  50  13
..         ...              ...         ...               ...   ...  ..  ..
600     203897      Zach LaVine  1610612741               CHI  27.0  67  37
601    1630285   Zavier Simpson  1610612760               OKC  25.0   4   1
602    1630192       Zeke Nnaji  1610612743               DEN  21.0  41  24
603    1630533  Ziaire Williams  1610612763               MEM  20.0  62  41
604    1629597   Zylan Cheatham  1610612762               UTA  26.0   1   0

      L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    29  0.613  31.7  ...  5.9  2.5  1.8  0.6  0.6   0.7  2.0  2.7  15.0
1     0  1.000   2.8  ...  0.2  0.0  0.3  0.0  0.3   0.3  0.3  0.0   0.3
2    29  0.540  16.2  ...  1.9  2.4  1.1  0.7  0.1   0.3  1.5  1.2   6.3
3    20  0.615  11.0  ...  1.7  0.4  0.6  0.4  0.1   0.0  1.3  0.5   3.8
4    37  0.260  24.2  ...  3.6  1.4  1.1  0.6  0.2   0.4  1.9  1.3   8.3
..   ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
600  30  0.552  34.7  ...  4.6  4.5  2.6  0.6  0.3   0.9  1.8  4.0  24.4
601   3  0.250  43.5  ...  5.3  7.5  2.5  1.3  1.0   1.8  3.8  2.0  11.0
602  17  0.585  17.0  ...  3.6  0.4  0.6  0.4  0.3   0.5  1.9  1.3   6.6
603  21  0.661  21.7  ...  2.1  1.0  0.7  0.6  0.2   0.3  1.8  0.8   8.1
604   1  0.000   5.2  ...  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0   0.0

     PLUS_MINUS
0           4.3
1          -3.3
2          -0.6
3           0.4
4          -4.7
..          ...
600        -0.4
601       -23.8
602        -1.1
603         2.0
604       -13.0

[605 rows x 31 columns]

In [18]:
# set the desired season and team
season = "2009-10"

# retrieve data from the API
player_stats = LeagueDashPlayerStats(season=season,per_mode_detailed="PerGame")
player_stats_2010 = player_stats.get_data_frames()[0]
player_stats_2010 = player_stats_2010[columns]

In [ ]:
# create an empty list to store the data for each season
data = []

# loop through the desired seasons and retrieve the data
for season in range(1995, 2022):
    season_str = str(season) + '-' + str(season+1)[-2:]
    player_stats5 = LeagueDashPlayerStats(season=season_str, per_mode_detailed="PerGame")
    player_stats_df5 = player_stats5.get_data_frames()[0]
    player_stats_df5=player_stats_df5[columns]
    
    data.append(player_stats_df5)
    
    print(player_stats_df5) # view the data for each season

Empty DataFrame
Columns: [PLAYER_ID, PLAYER_NAME, TEAM_ID, TEAM_ABBREVIATION, AGE, GP, W, L, W_PCT, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS]
Index: []

[0 rows x 31 columns]
     PLAYER_ID      PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W  \
0          920       A.C. Green  1610612742               DAL  33.0  83  23
1          243      Aaron McKie  1610612765               DET  24.0  83  48
2         1425   Aaron Williams  1610612763               VAN  25.0  33   4
3          768        Acie Earl  1610612749               MIL  27.0  47  14
4          228       Adam Keefe  1610612762               UTA  27.0  62  48
..         ...              ...         ...               ...   ...  ..  ..
436        335  Willie Anderson  1610612748               MIA  30.0  28  22
437        416    Willie Burton  1610612737               ATL  29.0  24  15
438       1365  Xavier McDaniel  1610612751               NJN  34.0  62  19
439        212       Yinka Dare  1610612751               NJN  24.0  41  12
440        440        Zan Tabak  1610612761               TOR  27.0  13   6

      L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD  PTS  \
0    60  0.277  30.1  ...  7.9  0.8  0.9  0.8  0.2   0.5  1.7  0.0  7.2
1    35  0.578  19.6  ...  2.7  1.9  1.1  0.9  0.3   0.4  1.6  0.0  5.2
2    29  0.121  17.0  ...  4.3  0.5  1.0  0.5  0.9   0.2  2.2  0.0  6.2
3    33  0.298  10.6  ...  2.0  0.4  0.7  0.3  0.6   0.2  1.3  0.0  4.0
4    14  0.774  14.8  ...  3.5  0.5  0.7  0.5  0.2   0.2  1.6  0.0  3.8
..   ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...
436   6  0.786  10.7  ...  1.5  1.2  0.7  0.5  0.1   0.0  1.3  0.0  3.0
437   9  0.625  15.9  ...  1.7  0.5  1.1  0.3  0.1   0.5  2.3  0.0  6.2
438  43  0.306  18.9  ...  5.1  1.0  1.1  0.6  0.3   0.4  2.3  0.0  5.6
439  29  0.293   7.7  ...  2.0  0.1  0.5  0.1  0.7   0.1  1.2  0.0  1.4
440   7  0.462  16.7  ...  3.8  1.1  1.6  0.5  0.8   0.4  2.7  0.1  6.5

     PLUS_MINUS
0          -4.2
1           1.6
2          -3.2
3          -1.3
4           2.0
..          ...
436        -0.5
437        -2.4
438         0.1
439         0.1
440        -3.4

[441 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          920          A.C. Green  1610612742               DAL  34.0  82
1          243         Aaron McKie  1610612755               PHI  25.0  81
2         1425      Aaron Williams  1610612760               SEA  26.0  65
3          228          Adam Keefe  1610612762               UTA  28.0  80
4         1502        Adonal Foyle  1610612744               GSW  23.0  55
..         ...                 ...         ...               ...   ...  ..
434        416       Willie Burton  1610612759               SAS  30.0  13
435       1365     Xavier McDaniel  1610612751               NJN  35.0  20
436        212          Yinka Dare  1610612751               NJN  25.0  10
437        440           Zan Tabak  1610612738               BOS  28.0  57
438        980  Zydrunas Ilgauskas  1610612739               CLE  23.0  82

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    20  62  0.244  32.3  ...  8.1  1.5  0.8  1.0  0.3   0.4  1.9  0.0   7.3
1    34  47  0.420  22.4  ...  2.9  2.2  0.9  1.2  0.2   0.4  2.0  0.0   4.1
2    49  16  0.754  11.6  ...  2.3  0.2  0.8  0.3  0.6   0.4  1.8  0.0   4.6
3    61  19  0.763  25.6  ...  5.5  1.1  0.9  0.7  0.3   0.7  2.2  0.0   7.8
4     9  46  0.164  12.0  ...  3.3  0.3  0.9  0.2  0.9   0.3  1.7  0.0   3.0
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
434  10   3  0.769   3.2  ...  0.7  0.1  0.1  0.2  0.2   0.0  0.5  0.0   2.1
435  11   9  0.550   8.9  ...  1.6  0.5  0.4  0.2  0.1   0.1  1.2  0.1   1.3
436   6   4  0.600   5.9  ...  1.7  0.1  0.2  0.0  0.2   0.5  0.9  0.0   1.2
437  16  41  0.281  17.2  ...  3.7  0.8  1.1  0.4  0.7   0.3  2.9  0.0   5.4
438  47  35  0.573  29.0  ...  8.8  0.9  1.8  0.6  1.6   0.7  3.5  0.0  13.9

     PLUS_MINUS
0          -4.6
1           0.3
2           1.0
3           5.4
4          -3.1
..          ...
434        -0.3
435        -0.6
436        -2.3
437        -3.8
438         2.6

[439 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          920          A.C. Green  1610612742               DAL  35.0  50
1          243         Aaron McKie  1610612755               PHI  26.0  50
2         1425      Aaron Williams  1610612760               SEA  27.0  40
3          228          Adam Keefe  1610612762               UTA  29.0  44
4         1502        Adonal Foyle  1610612744               GSW  24.0  44
..         ...                 ...         ...               ...   ...  ..
435        445       Wesley Person  1610612739               CLE  28.0  45
436        781         Will Perdue  1610612759               SAS  33.0  37
437       1061  William Cunningham  1610612751               NJN  25.0  16
438        416       Willie Burton  1610612766               CHH  31.0   3
439        980  Zydrunas Ilgauskas  1610612739               CLE  24.0   5

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    19  31  0.380  18.5  ...  4.6  0.5  0.4  0.6  0.2   0.3  1.4  0.0   4.9
1    28  22  0.560  19.2  ...  2.8  2.0  1.1  1.3  0.1   0.1  1.8  0.0   4.8
2    19  21  0.475  11.5  ...  3.2  0.6  0.8  0.4  0.6   0.3  1.9  0.0   4.0
3    32  12  0.727  14.6  ...  3.2  0.6  0.8  0.4  0.3   0.4  1.4  0.0   4.0
4    16  28  0.364  13.9  ...  4.4  0.4  0.7  0.3  1.0   0.4  2.0  0.0   2.9
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
435  22  23  0.489  29.8  ...  3.2  1.8  0.9  0.8  0.4   0.4  1.2  0.0  11.2
436  33   4  0.892  12.1  ...  3.7  0.5  0.6  0.2  0.3   0.2  1.7  0.0   2.4
437   7   9  0.438  10.2  ...  1.8  0.1  0.3  0.1  0.7   0.1  1.9  0.1   0.4
438   1   2  0.333   6.0  ...  2.0  0.0  0.3  0.0  0.0   1.0  0.7  0.0   1.3
439   2   3  0.400  34.1  ...  8.8  0.8  1.8  0.8  1.4   0.8  4.8  0.0  15.2

     PLUS_MINUS
0          -1.6
1          -1.3
2          -2.5
3           1.2
4          -1.0
..          ...
435        -2.0
436         0.6
437        -2.9
438         1.0
439        -2.4

[440 rows x 31 columns]
     PLAYER_ID     PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W  \
0          920      A.C. Green  1610612747               LAL  36.0  82  67
1         1920   A.J. Bramlett  1610612739               CLE  23.0   8   3
2          243     Aaron McKie  1610612755               PHI  27.0  82  49
3         1425  Aaron Williams  1610612764               WAS  28.0  81  29
4          228      Adam Keefe  1610612762               UTA  30.0  62  41
..         ...             ...         ...               ...   ...  ..  ..
434       1943    Wayne Turner  1610612738               BOS  24.0   3   3
435        445   Wesley Person  1610612739               CLE  29.0  79  29
436        781     Will Perdue  1610612741               CHI  34.0  67  11
437       1895   William Avery  1610612750               MIN  20.0  59  37
438        440       Zan Tabak  1610612754               IND  30.0  18  11

      L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD  PTS  \
0    15  0.817  23.5  ...  5.9  1.0  0.6  0.6  0.2   0.3  1.5  0.2  5.0
1     5  0.375   7.6  ...  2.8  0.0  0.4  0.1  0.0   0.3  1.6  0.3  1.0
2    33  0.598  23.8  ...  3.0  2.9  1.4  1.3  0.2   0.5  2.4  0.1  8.0
3    52  0.358  19.1  ...  5.0  0.7  1.0  0.5  1.1   0.6  2.9  0.2  7.6
4    21  0.661   9.8  ...  2.2  0.5  0.7  0.3  0.2   0.3  1.5  0.1  2.2
..   ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...
434   0  1.000  13.4  ...  1.0  1.7  1.0  0.0  0.0   0.0  1.3  0.3  1.3
435  50  0.367  26.0  ...  3.4  1.8  0.8  0.5  0.2   0.3  1.5  0.1  9.2
436  56  0.164  15.1  ...  3.9  0.9  1.2  0.2  0.6   0.3  1.9  0.3  2.5
437  22  0.627   8.1  ...  0.7  1.5  0.7  0.2  0.0   0.2  1.0  0.0  2.6
438   7  0.611   6.3  ...  1.8  0.2  0.6  0.2  0.5   0.3  0.7  0.0  2.1

     PLUS_MINUS
0           4.0
1          -5.3
2           0.6
3           0.4
4          -0.6
..          ...
434         0.7
435        -1.1
436        -3.3
437        -1.8
438         0.8

[439 rows x 31 columns]

     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          920          A.C. Green  1610612748               MIA  37.0  82
1         2062         A.J. Guyton  1610612741               CHI  23.0  33
2          243         Aaron McKie  1610612755               PHI  28.0  76
3         1425      Aaron Williams  1610612751               NJN  29.0  82
4          228          Adam Keefe  1610612744               GSW  31.0  67
..         ...                 ...         ...               ...   ...  ..
436        781         Will Perdue  1610612757               POR  35.0  13
437       1895       William Avery  1610612750               MIN  21.0  55
438        440           Zan Tabak  1610612754               IND  31.0  55
439       1985     Zendon Hamilton  1610612746               LAC  26.0   3
440        980  Zydrunas Ilgauskas  1610612739               CLE  26.0  24

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    50  32  0.610  17.2  ...  3.8  0.5  0.5  0.4  0.1   0.4  1.5  0.0   4.5
1     6  27  0.182  19.0  ...  1.1  1.9  0.7  0.3  0.2   0.1  1.1  0.0   6.0
2    51  25  0.671  31.5  ...  4.1  5.0  2.7  1.4  0.1   0.7  2.3  0.0  11.6
3    26  56  0.317  28.5  ...  7.2  1.1  1.6  0.7  1.4   0.9  3.9  0.0  10.2
4    14  53  0.209  12.6  ...  3.1  0.5  0.6  0.4  0.3   0.3  1.5  0.0   2.5
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
436  10   3  0.769   4.3  ...  1.4  0.2  0.0  0.2  0.2   0.1  0.6  0.0   1.1
437  32  23  0.582   8.4  ...  0.5  1.4  0.8  0.2  0.1   0.2  0.9  0.0   2.8
438  29  26  0.527  14.1  ...  3.9  0.6  1.0  0.2  0.5   0.2  2.3  0.0   3.9
439   1   2  0.333   6.4  ...  2.7  0.0  0.7  0.0  0.0   0.3  1.3  0.0   3.0
440  15   9  0.625  25.6  ...  6.7  0.8  2.5  0.6  1.5   0.7  3.3  0.0  11.7

     PLUS_MINUS
0           1.3
1          -4.4
2           4.4
3          -4.6
4          -2.6
..          ...
436         0.2
437        -1.1
438         0.1
439        -3.0
440        -0.3

[441 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0         2062         A.J. Guyton  1610612741               CHI  24.0  45
1          243         Aaron McKie  1610612755               PHI  29.0  48
2         1425      Aaron Williams  1610612751               NJN  30.0  82
3         1502        Adonal Foyle  1610612744               GSW  27.0  79
4         1559      Adrian Griffin  1610612742               DAL  27.0  58
..         ...                 ...         ...               ...   ...  ..
435       1895       William Avery  1610612750               MIN  22.0  28
436       2216       Zach Randolph  1610612757               POR  20.0  41
437       1442      Zeljko Rebraca  1610612765               DET  30.0  74
438       1985     Zendon Hamilton  1610612743               DEN  27.0  54
439        980  Zydrunas Ilgauskas  1610612739               CLE  27.0  62

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    10  35  0.222  13.4  ...  1.0  1.8  0.8  0.2  0.2   0.1  0.5  0.0   5.4
1    26  22  0.542  30.6  ...  4.0  3.7  1.9  1.2  0.3   0.9  1.5  0.0  12.2
2    52  30  0.634  18.9  ...  4.1  0.9  1.0  0.4  0.9   0.5  2.6  0.0   7.2
3    19  60  0.241  18.8  ...  4.9  0.5  1.0  0.5  2.1   0.4  2.3  0.0   4.8
4    40  18  0.690  23.9  ...  3.9  1.8  0.7  1.3  0.2   0.4  2.4  0.0   7.2
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
435  17  11  0.607   9.3  ...  0.9  1.3  0.7  0.3  0.0   0.3  0.6  0.0   2.5
436  22  19  0.537   5.8  ...  1.7  0.3  0.4  0.2  0.1   0.3  0.7  0.0   2.8
437  46  28  0.622  15.9  ...  3.9  0.5  1.1  0.4  1.0   0.4  2.6  0.0   6.9
438  17  37  0.315  15.7  ...  4.7  0.3  1.1  0.4  0.3   0.9  1.9  0.0   6.0
439  23  39  0.371  21.5  ...  5.4  1.1  1.5  0.3  1.4   0.7  3.0  0.0  11.1

     PLUS_MINUS
0          -1.0
1           2.4
2           1.5
3          -2.6
4           2.6
..          ...
435        -0.7
436        -0.5
437         0.8
438        -4.1
439        -1.6

[440 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0         2062         A.J. Guyton  1610612744               GSW  25.0   2
1          243         Aaron McKie  1610612755               PHI  30.0  80
2         1425      Aaron Williams  1610612751               NJN  31.0  81
3         2492     Adam Harrington  1610612743               DEN  22.0  19
4         1502        Adonal Foyle  1610612744               GSW  28.0  82
..         ...                 ...         ...               ...   ...  ..
423       2397            Yao Ming  1610612745               HOU  22.0  82
424       2216       Zach Randolph  1610612757               POR  21.0  77
425       1442      Zeljko Rebraca  1610612765               DET  31.0  30
426       1985     Zendon Hamilton  1610612761               TOR  28.0   3
427        980  Zydrunas Ilgauskas  1610612739               CLE  28.0  81

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0     1   1  0.500   4.3  ...  0.0  1.0  0.5  0.5  0.0   0.5  0.0  0.0   0.0
1    47  33  0.588  29.7  ...  4.4  3.5  1.4  1.6  0.1   0.9  2.2  0.0   9.0
2    49  32  0.605  19.8  ...  4.1  1.1  1.0  0.3  0.7   0.6  2.5  0.0   6.2
3    13   6  0.684   5.8  ...  0.4  0.6  0.1  0.1  0.1   0.2  0.4  0.0   1.6
4    38  44  0.463  21.8  ...  6.0  0.5  0.9  0.5  2.5   0.3  2.6  0.0   5.4
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
423  43  39  0.524  29.0  ...  8.2  1.7  2.1  0.4  1.8   0.7  2.8  0.0  13.5
424  48  29  0.623  16.9  ...  4.5  0.5  0.8  0.5  0.2   0.9  1.8  0.0   8.4
425  20  10  0.667  16.3  ...  3.1  0.3  1.0  0.2  0.6   0.3  2.6  0.0   6.6
426   2   1  0.667   3.7  ...  1.3  0.0  0.3  0.3  0.0   0.0  0.7  0.0   2.0
427  17  64  0.210  30.0  ...  7.5  1.6  2.6  0.7  1.9   1.0  3.4  0.0  17.2

     PLUS_MINUS
0          -1.0
1           2.6
2           0.6
3          -1.8
4           0.9
..          ...
423         1.7
424        -1.2
425         1.0
426         0.7
427        -4.6

[428 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          243         Aaron McKie  1610612755               PHI  31.0  75
1         1425      Aaron Williams  1610612751               NJN  32.0  72
2         1502        Adonal Foyle  1610612744               GSW  29.0  44
3         1559      Adrian Griffin  1610612745               HOU  29.0  19
4         1733       Al Harrington  1610612754               IND  24.0  79
..         ...                 ...         ...               ...   ...  ..
437       2585       Zaza Pachulia  1610612753               ORL  20.0  59
438       1442      Zeljko Rebraca  1610612737               ATL  32.0  24
439       1985     Zendon Hamilton  1610612755               PHI  29.0  46
440       2565      Zoran Planinic  1610612751               NJN  21.0  49
441        980  Zydrunas Ilgauskas  1610612739               CLE  29.0  81

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    30  45  0.400  28.2  ...  3.4  2.6  1.4  1.1  0.3   0.7  1.9  0.0   9.2
1    39  33  0.542  18.6  ...  4.1  1.1  1.2  0.5  0.6   0.3  2.6  0.0   6.3
2    21  23  0.477  13.1  ...  3.8  0.4  0.5  0.1  1.0   0.3  1.5  0.0   3.1
3    13   6  0.684   6.4  ...  1.0  0.5  0.2  0.4  0.1   0.0  0.9  0.0   0.6
4    58  21  0.734  30.9  ...  6.4  1.7  2.1  1.0  0.3   1.0  3.2  0.0  13.3
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
437  13  46  0.220  11.2  ...  2.9  0.2  0.6  0.4  0.2   0.4  1.5  0.0   3.3
438   9  15  0.375  11.2  ...  2.4  0.3  0.7  0.2  0.5   0.2  2.2  0.1   3.8
439  16  30  0.348  10.2  ...  3.2  0.3  0.6  0.2  0.2   0.3  1.6  0.0   3.7
440  31  18  0.633   9.5  ...  1.1  1.4  0.7  0.3  0.1   0.2  1.4  0.0   3.1
441  34  47  0.420  31.4  ...  8.1  1.3  2.0  0.5  2.5   1.0  3.4  0.0  15.3

     PLUS_MINUS
0          -0.6
1          -0.7
2          -1.9
3          -2.5
4           0.9
..          ...
437        -1.1
438        -1.5
439        -1.4
440        -1.6
441        -2.1

[442 rows x 31 columns]

     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          243         Aaron McKie  1610612755               PHI  32.0  68
1         1425      Aaron Williams  1610612761               TOR  33.0  42
2         1502        Adonal Foyle  1610612744               GSW  30.0  78
3         1559      Adrian Griffin  1610612741               CHI  30.0  69
4         1733       Al Harrington  1610612737               ATL  25.0  66
..         ...                 ...         ...               ...   ...  ..
459       2585       Zaza Pachulia  1610612749               MIL  21.0  74
460       1442      Zeljko Rebraca  1610612746               LAC  33.0  58
461       1985     Zendon Hamilton  1610612749               MIL  30.0  16
462       2565      Zoran Planinic  1610612751               NJN  22.0  43
463        980  Zydrunas Ilgauskas  1610612739               CLE  30.0  78

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    35  33  0.515  16.6  ...  2.5  1.5  0.5  0.7  0.3   0.2  1.7  0.0   2.2
1    13  29  0.310   7.4  ...  1.4  0.2  0.4  0.1  0.2   0.2  1.7  0.0   1.7
2    31  47  0.397  21.8  ...  5.5  0.7  0.7  0.3  2.0   0.3  2.6  0.0   4.5
3    38  31  0.551   9.5  ...  2.1  0.8  0.4  0.6  0.1   0.1  1.1  0.0   2.2
4    10  56  0.152  38.6  ...  7.0  3.2  3.1  1.3  0.2   1.1  3.8  0.0  17.5
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
459  27  47  0.365  18.9  ...  5.1  0.8  0.9  0.6  0.5   0.6  2.2  0.0   6.2
460  27  31  0.466  16.0  ...  3.2  0.4  0.8  0.2  0.7   0.4  2.2  0.0   5.8
461   7   9  0.438  10.1  ...  2.6  0.4  0.8  0.3  0.1   0.5  1.6  0.0   3.2
462  20  23  0.465  11.9  ...  1.6  1.0  1.0  0.6  0.0   0.4  1.8  0.0   5.0
463  40  38  0.513  33.5  ...  8.6  1.3  2.4  0.7  2.1   1.0  4.0  0.0  16.9

     PLUS_MINUS
0           0.2
1          -3.2
2          -0.3
3           0.6
4          -7.8
..          ...
459        -0.1
460         0.3
461        -2.1
462        -1.0
463         1.6

[464 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          243         Aaron McKie  1610612747               LAL  33.0  14
1       101223         Aaron Miles  1610612744               GSW  23.0  19
2         1425      Aaron Williams  1610612740               NOK  34.0  48
3         1502        Adonal Foyle  1610612744               GSW  31.0  77
4         1559      Adrian Griffin  1610612742               DAL  31.0  52
..         ...                 ...         ...               ...   ...  ..
453       2585       Zaza Pachulia  1610612737               ATL  22.0  78
454       1442      Zeljko Rebraca  1610612746               LAC  34.0  29
455       1985     Zendon Hamilton  1610612755               PHI  31.0  12
456       2565      Zoran Planinic  1610612751               NJN  23.0  56
457        980  Zydrunas Ilgauskas  1610612739               CLE  31.0  78

      W   L  W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0     9   5  0.643   8.7  ...  1.4  0.8  0.1  0.4  0.0   0.0  0.5  0.1   0.5
1    13   6  0.684   6.2  ...  0.7  1.3  0.6  0.2  0.1   0.2  0.7  0.4   0.8
2    21  27  0.438  16.5  ...  3.8  0.4  0.6  0.4  0.4   0.4  2.9  1.0   4.6
3    32  45  0.416  23.7  ...  5.5  0.4  1.0  0.6  1.6   0.3  2.8  1.1   4.5
4    40  12  0.769  23.9  ...  4.4  1.7  0.8  1.0  0.2   0.3  2.2  0.8   4.6
..   ..  ..    ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
453  26  52  0.333  31.4  ...  7.9  1.7  2.3  1.1  0.5   1.2  3.7  4.4  11.7
454  18  11  0.621  14.2  ...  2.2  0.3  0.8  0.2  0.7   0.2  2.0  1.8   4.7
455   8   4  0.667   4.0  ...  0.9  0.0  0.5  0.3  0.0   0.3  0.4  0.8   2.2
456  31  25  0.554  10.6  ...  1.3  0.9  0.8  0.4  0.1   0.3  1.6  1.1   3.4
457  48  30  0.615  29.3  ...  7.6  1.2  2.0  0.5  1.7   0.7  3.6  3.8  15.6

     PLUS_MINUS
0          -1.4
1          -0.2
2          -0.8
3          -0.4
4           3.5
..          ...
453        -2.9
454        -4.2
455        -1.6
456        -1.2
457         2.4

[458 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0          243         Aaron McKie  1610612747               LAL  34.0  10
1         1425      Aaron Williams  1610612746               LAC  35.0  38
2       200747       Adam Morrison  1610612766               CHA  22.0  78
3         1502        Adonal Foyle  1610612744               GSW  32.0  48
4         1559      Adrian Griffin  1610612741               CHI  32.0  54
..         ...                 ...         ...               ...   ...  ..
453       2397            Yao Ming  1610612745               HOU  26.0  48
454     101117    Yaroslav Korolev  1610612746               LAC  20.0  10
455       2216       Zach Randolph  1610612757               POR  25.0  68
456       2585       Zaza Pachulia  1610612737               ATL  23.0  72
457        980  Zydrunas Ilgauskas  1610612739               CLE  32.0  78

      W   L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0     4   6  0.400  13.1  ...   1.8  1.3  0.8  0.4  0.0   0.0  1.4  0.1   2.2
1    15  23  0.395   9.8  ...   2.2  0.2  0.5  0.2  0.4   0.1  1.5  0.7   2.0
2    30  48  0.385  29.8  ...   2.9  2.1  1.7  0.4  0.1   0.5  2.3  1.9  11.8
3    19  29  0.396   9.9  ...   2.6  0.4  0.5  0.2  1.0   0.1  1.3  0.5   2.2
4    32  22  0.593  10.8  ...   2.0  1.1  0.7  0.6  0.1   0.2  1.4  0.3   2.5
..   ..  ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
453  32  16  0.667  33.8  ...   9.4  2.0  3.5  0.4  2.0   1.3  3.3  6.9  25.0
454   6   4  0.600   4.1  ...   0.3  0.4  0.1  0.3  0.0   0.1  0.0  0.3   1.2
455  25  43  0.368  35.7  ...  10.1  2.2  3.2  0.8  0.2   1.6  2.7  5.8  23.6
456  26  46  0.361  28.1  ...   6.9  1.5  2.3  1.1  0.5   1.0  3.7  3.8  12.2
457  48  30  0.615  27.3  ...   7.7  1.6  1.8  0.6  1.3   0.4  3.3  2.1  11.9

     PLUS_MINUS
0          -1.3
1          -0.4
2          -3.1
3          -1.1
4           1.4
..          ...
453         6.2
454        -2.3
455        -1.9
456        -1.4
457         3.3

[458 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0       201166        Aaron Brooks  1610612745               HOU  23.0  51
1       201189          Aaron Gray  1610612741               CHI  23.0  61
2         1425      Aaron Williams  1610612746               LAC  36.0  30
3       201151            Acie Law  1610612737               ATL  23.0  56
4         1502        Adonal Foyle  1610612753               ORL  33.0  82
..         ...                 ...         ...               ...   ...  ..
446       2397            Yao Ming  1610612745               HOU  27.0  55
447     201146         Yi Jianlian  1610612749               MIL  20.0  66
448       2216       Zach Randolph  1610612752               NYK  26.0  69
449       2585       Zaza Pachulia  1610612737               ATL  24.0  62
450        980  Zydrunas Ilgauskas  1610612739               CLE  33.0  73

      W   L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    36  15  0.706  11.9  ...   1.1  1.7  0.9  0.3  0.1   0.2  1.4  1.0   5.2
1    23  38  0.377  10.0  ...   2.8  0.7  0.9  0.3  0.3   0.5  1.9  1.3   4.3
2     9  21  0.300   9.9  ...   2.0  0.3  0.4  0.4  0.5   0.2  1.5  0.7   2.3
3    25  31  0.446  15.5  ...   1.0  2.0  1.0  0.5  0.0   0.4  1.3  1.0   4.2
4    52  30  0.634   9.4  ...   2.5  0.2  0.4  0.2  0.5   0.3  1.1  0.5   1.9
..   ..  ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
446  36  19  0.655  37.2  ...  10.8  2.3  3.3  0.5  2.0   1.1  3.1  6.1  22.0
447  24  42  0.364  24.9  ...   5.2  0.8  1.4  0.5  0.8   0.8  2.3  1.8   8.6
448  23  46  0.333  32.5  ...  10.3  2.0  2.7  0.9  0.2   1.1  2.8  3.8  17.6
449  28  34  0.452  15.2  ...   4.0  0.6  1.1  0.4  0.2   0.4  2.3  2.0   5.2
450  41  32  0.562  30.4  ...   9.3  1.4  1.8  0.5  1.6   0.6  3.4  2.2  14.1

     PLUS_MINUS
0          -0.1
1          -0.3
2          -3.3
3          -2.1
4          -0.2
..          ...
446         3.5
447        -3.5
448        -4.0
449        -0.8
450         0.8

[451 rows x 31 columns]

     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0       201166        Aaron Brooks  1610612745               HOU  24.0  80
1       201189          Aaron Gray  1610612741               CHI  24.0  56
2       201151            Acie Law  1610612737               ATL  24.0  55
3       200747       Adam Morrison  1610612747               LAL  24.0  52
4         1502        Adonal Foyle  1610612753               ORL  34.0  10
..         ...                 ...         ...               ...   ...  ..
440       2397            Yao Ming  1610612745               HOU  28.0  77
441     201146         Yi Jianlian  1610612751               NJN  21.0  61
442       2216       Zach Randolph  1610612746               LAC  27.0  50
443       2585       Zaza Pachulia  1610612737               ATL  25.0  77
444        980  Zydrunas Ilgauskas  1610612739               CLE  34.0  65

      W   L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    52  28  0.650  25.0  ...   2.0  3.0  1.6  0.6  0.1   0.7  1.9  1.9  11.2
1    26  30  0.464  12.8  ...   3.9  0.8  0.7  0.3  0.3   0.4  2.4  0.9   3.5
2    33  22  0.600  10.2  ...   1.1  1.6  0.5  0.2  0.1   0.4  0.8  0.9   2.9
3    23  29  0.442  13.7  ...   1.5  0.8  0.6  0.2  0.1   0.2  1.5  0.5   4.0
4     6   4  0.600   6.2  ...   2.6  0.1  0.3  0.0  0.8   0.0  0.5  0.2   1.7
..   ..  ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
440  50  27  0.649  33.6  ...   9.9  1.8  3.0  0.4  1.9   1.2  3.3  5.0  19.7
441  26  35  0.426  23.3  ...   5.3  1.0  1.1  0.5  0.6   0.5  2.6  1.5   8.6
442  19  31  0.380  35.1  ...  10.1  2.1  2.3  0.9  0.3   1.1  2.7  4.2  20.8
443  45  32  0.584  19.1  ...   5.7  0.7  1.2  0.5  0.3   0.5  2.7  2.5   6.2
444  55  10  0.846  27.2  ...   7.5  1.0  1.4  0.4  1.3   0.5  2.8  1.9  12.9

     PLUS_MINUS
0           2.1
1          -0.9
2           0.0
3          -2.1
4          -1.0
..          ...
440         5.8
441        -1.8
442        -2.9
443         1.6
444         7.5

[445 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0       201985            AJ Price  1610612754               IND  23.0  56
1       201166        Aaron Brooks  1610612745               HOU  25.0  82
2       201189          Aaron Gray  1610612740               NOH  25.0  32
3       201151            Acie Law  1610612741               CHI  25.0  26
4       200747       Adam Morrison  1610612747               LAL  25.0  31
..         ...                 ...         ...               ...   ...  ..
437     200821    Yakhouba Diawara  1610612748               MIA  27.0   6
438     201146         Yi Jianlian  1610612751               NJN  22.0  52
439       2216       Zach Randolph  1610612763               MEM  28.0  81
440       2585       Zaza Pachulia  1610612737               ATL  26.0  78
441        980  Zydrunas Ilgauskas  1610612739               CLE  35.0  64

      W   L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    23  33  0.411  15.5  ...   1.6  1.9  1.1  0.6  0.1   0.3  0.9  1.4   7.3
1    42  40  0.512  35.6  ...   2.6  5.3  2.8  0.8  0.2   1.0  2.4  3.0  19.6
2    11  21  0.344   9.7  ...   3.3  0.7  0.6  0.3  0.3   0.3  1.7  0.6   3.3
3    11  15  0.423   9.0  ...   0.7  1.0  0.7  0.4  0.0   0.5  0.6  1.2   4.3
4    23   8  0.742   7.8  ...   1.0  0.6  0.3  0.1  0.1   0.2  0.5  0.2   2.4
..   ..  ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
437   5   1  0.833   7.4  ...   0.7  0.5  0.5  0.2  0.0   0.2  1.3  0.0   0.8
438  10  42  0.192  31.8  ...   7.2  0.9  1.5  0.7  1.0   0.8  3.3  2.7  12.0
439  39  42  0.481  37.7  ...  11.7  1.8  2.1  1.0  0.4   1.5  2.8  4.5  20.8
440  50  28  0.641  14.0  ...   3.8  0.5  0.7  0.5  0.4   0.4  2.4  1.4   4.3
441  47  17  0.734  20.9  ...   5.4  0.8  1.0  0.2  0.8   0.3  2.9  1.2   7.4

     PLUS_MINUS
0           0.9
1          -0.3
2          -0.4
3           0.8
4          -1.2
..          ...
437        -0.5
438        -4.3
439         0.2
440        -0.2
441         3.5

[442 rows x 31 columns]
     PLAYER_ID         PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
0       201985            AJ Price  1610612754               IND  24.0  50
1       201166        Aaron Brooks  1610612756               PHX  26.0  59
2       201189          Aaron Gray  1610612740               NOH  26.0  41
3       201151            Acie Law  1610612744               GSW  26.0  51
4         1733       Al Harrington  1610612743               DEN  31.0  73
..         ...                 ...         ...               ...   ...  ..
447     201146         Yi Jianlian  1610612764               WAS  23.0  63
448     202220      Zabian Dowdell  1610612756               PHX  26.0  24
449       2216       Zach Randolph  1610612763               MEM  29.0  75
450       2585       Zaza Pachulia  1610612737               ATL  27.0  79
451        980  Zydrunas Ilgauskas  1610612748               MIA  36.0  72

      W   L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    22  28  0.440  15.9  ...   1.4  2.2  1.1  0.6  0.0   0.2  1.2  1.5   6.5
1    26  33  0.441  21.8  ...   1.3  3.9  1.7  0.6  0.1   0.7  1.9  2.1  10.7
2    21  20  0.512  12.9  ...   4.2  0.4  0.8  0.3  0.3   0.3  2.3  0.7   3.1
3    20  31  0.392  14.2  ...   1.2  1.6  0.8  0.6  0.0   0.4  1.2  1.2   4.2
4    45  28  0.616  22.8  ...   4.5  1.4  1.5  0.5  0.1   0.6  2.8  1.5  10.5
..   ..  ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
447  17  46  0.270  17.6  ...   3.9  0.4  0.8  0.4  0.5   0.3  1.8  1.1   5.6
448  14  10  0.583  12.2  ...   0.8  2.1  1.2  0.8  0.1   0.1  1.3  0.9   5.0
449  43  32  0.573  36.3  ...  12.2  2.2  2.0  0.8  0.3   1.5  2.3  4.4  20.1
450  43  36  0.544  15.7  ...   4.2  0.7  0.9  0.4  0.3   0.6  2.3  2.1   4.4
451  51  21  0.708  15.9  ...   4.0  0.4  0.7  0.3  0.8   0.2  2.6  0.6   5.0

     PLUS_MINUS
0           0.5
1          -2.8
2           0.7
3          -2.6
4           1.8
..          ...
447        -3.5
448        -1.8
449         3.5
450        -1.7
451         2.9

[452 rows x 31 columns]
     PLAYER_ID    PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  \
0       201985       AJ Price  1610612754               IND  25.0  44  27  17
1       201189     Aaron Gray  1610612761               TOR  27.0  49  17  32
2         1733  Al Harrington  1610612743               DEN  32.0  64  36  28
3       201143     Al Horford  1610612737               ATL  26.0  11   7   4
4         2744   Al Jefferson  1610612762               UTA  27.0  61  32  29
..         ...            ...         ...               ...   ...  ..  ..  ..
473     202333   Xavier Henry  1610612740               NOH  21.0  45  18  27
474     202918   Xavier Silas  1610612755               PHI  24.0   2   1   1
475     201146    Yi Jianlian  1610612742               DAL  24.0  30  15  15
476       2216  Zach Randolph  1610612763               MEM  30.0  28  17  11
477       2585  Zaza Pachulia  1610612737               ATL  28.0  58  34  24

     W_PCT   MIN  ...  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    0.614  12.9  ...  1.4  2.0  0.7  0.5  0.0   0.1  0.7  0.7   3.9
1    0.347  16.6  ...  5.7  0.6  1.0  0.4  0.3   0.3  2.6  0.8   3.9
2    0.563  27.5  ...  6.1  1.4  1.8  0.9  0.2   0.8  2.8  2.2  14.2
3    0.636  31.6  ...  7.0  2.2  1.5  0.9  1.3   0.6  1.9  2.5  12.4
4    0.525  34.0  ...  9.6  2.2  1.0  0.8  1.7   1.0  2.5  2.3  19.2
..     ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...
473  0.400  16.9  ...  2.4  0.8  0.8  0.6  0.2   0.5  1.3  1.4   5.3
474  0.500  19.4  ...  2.0  1.5  1.5  0.0  0.0   0.5  2.5  2.5   5.5
475  0.500   6.8  ...  1.6  0.2  0.5  0.2  0.3   0.3  0.8  0.5   2.6
476  0.607  26.2  ...  8.0  1.7  1.4  0.8  0.1   0.8  2.0  2.7  11.6
477  0.586  28.3  ...  7.9  1.4  1.4  0.9  0.5   0.7  3.0  2.9   7.8

     PLUS_MINUS
0           0.8
1          -3.1
2           2.6
3           4.7
4           2.6
..          ...
473        -0.7
474        -7.0
475        -2.1
476         4.1
477         1.4

[478 rows x 31 columns]

     PLAYER_ID      PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W  \
0       201985         AJ Price  1610612764               WAS  26.0  57  21
1       201166     Aaron Brooks  1610612745               HOU  28.0  53  20
2       201189       Aaron Gray  1610612761               TOR  28.0  42  14
3         1733    Al Harrington  1610612753               ORL  33.0  10   3
4       201143       Al Horford  1610612737               ATL  27.0  74  42
..         ...              ...         ...               ...   ...  ..  ..
464       2584     Willie Green  1610612746               LAC  31.0  72  48
465     201163  Wilson Chandler  1610612743               DEN  26.0  43  33
466     202333     Xavier Henry  1610612740               NOH  22.0  50  16
467       2216    Zach Randolph  1610612763               MEM  31.0  76  51
468       2585    Zaza Pachulia  1610612737               ATL  29.0  52  29

      L  W_PCT   MIN  ...   REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  \
0    36  0.368  22.4  ...   2.0  3.6  1.1  0.6  0.1   0.2  1.3  1.2   7.7
1    33  0.377  18.8  ...   1.5  2.2  1.3  0.6  0.2   0.6  1.8  1.3   7.1
2    28  0.333  12.2  ...   3.2  0.8  0.9  0.2  0.1   0.3  2.0  0.9   2.8
3     7  0.300  11.9  ...   2.7  1.0  0.7  0.4  0.1   0.1  1.8  0.3   5.1
4    32  0.568  37.2  ...  10.2  3.2  2.0  1.1  1.1   0.5  2.2  2.6  17.4
..   ..    ...   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   ...
464  24  0.667  16.5  ...   1.3  0.8  0.4  0.4  0.2   0.2  1.3  0.4   6.3
465  10  0.767  25.1  ...   5.1  1.3  1.4  1.0  0.3   0.7  2.8  2.0  13.0
466  34  0.320  12.5  ...   1.8  0.3  0.6  0.3  0.1   0.4  1.4  1.5   3.9
467  25  0.671  34.3  ...  11.2  1.4  2.0  0.8  0.4   1.3  2.4  3.6  15.4
468  23  0.558  21.8  ...   6.5  1.5  1.3  0.7  0.2   0.7  2.5  2.1   5.9

     PLUS_MINUS
0          -1.1
1          -3.8
2          -2.1
3          -3.5
4           2.2
..          ...
464         1.3
465         4.1
466        -2.9
467         3.9
468        -0.5

[469 rows x 31 columns]

In [ ]:
# concatenate the data from each season into a single dataframe
all_seasons_data = pd.concat(data)
print(all_seasons_data)

In [ ]:
all_seasons_data

In [ ]:
all_seasons_data.columns

In [ ]:
import numpy as np 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/Users/Intel/Desktop/DATA SCIENCE/all_seasons.csv",index_col=0)
df_modificado=df.copy()
df_modificado["season"]=pd.to_datetime(df["season"].str[:-3] )

In [ ]:
#MERGE DATABASE

original_mas_api = pd.merge(all_seasons_data, df_modificado, how='left', left_on=['PLAYER_NAME', 'TEAM_ABBREVIATION', 'AGE'], right_on=['player_name', 'team_abbreviation', 'age'])
df_NBA=original_mas_api

In [ ]:
df_NBA.columns